#
# Copyright (c) 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARG BUILD_IMAGE=openvino/model_server-build:latest
FROM $BUILD_IMAGE

RUN http_proxy=${HTTP_PROXY} yum install -y lcov gcov genhtml
WORKDIR /ovms/src
ENV InferenceEngine_DIR=/opt/intel/openvino/deployment_tools/inference_engine/share/
ENV ngraph_DIR=/opt/intel/openvino/deployment_tools/ngraph/cmake/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib:/usr/local/lib:/usr/local/lib64:/opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/
ADD CMakeLists.txt /ovms/src
RUN export BAZEL_BUILD=$(ls /root/.cache/bazel/_bazel_root/ | egrep  '.{32}') && \
    grep '\.a\|\.o' /root/.cache/bazel/_bazel_root/$BAZEL_BUILD/execroot/ovms/bazel-out/k8-dbg/bin/src/ovms-2.params | grep -Ev '(ovms_test|libstdc\+\+|main.pic.o)' | \
    sed "s/^bazel-out\/k8-dbg\/bin\/external\//\/root\/\.cache\/bazel\/_bazel_root\/$BAZEL_BUILD\/execroot\/ovms\/bazel-out\/k8-dbg\/bin\/external\//g" | \
    sed "s/^bazel-out\/k8-dbg\/bin\/src\//\/root\/\.cache\/bazel\/_bazel_root\/$BAZEL_BUILD\/execroot\/ovms\/bazel-out\/k8-dbg\/bin\/src\//g" | \
    sed "s/^external\/boost\//\/root\/\.cache\/bazel\/_bazel_root\/$BAZEL_BUILD\/external\/boost\//g" | \
    sed "s/^external\//\/root\/\.cache\/bazel\/_bazel_root\/$BAZEL_BUILD\/external\//g" > ovms_libs.in && \
    cmake3 -DCMAKE_BUILD_TYPE=Debug .
RUN make -j4

#RUN make test
